name: CI

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        puppet_versions:
          - '5'
          - '6'

    name: Puppet ${{ matrix.puppet_versions }}
    steps:
    - uses: actions/checkout@v1
    - name: Install the Puppet PDK
      run: |
        wget https://apt.puppet.com/puppet-tools-release-bionic.deb
        sudo dpkg -i puppet-tools-release-bionic.deb
        sudo apt-get update 
        sudo apt-get install pdk
    - name: Syntax validation
      run: pdk validate --puppet-version ${{ matrix.puppet_versions }}
    - name: Unit tests
      run: pdk test unit --puppet-version ${{ matrix.puppet_versions }}
